### PR TITLE
add/local_storage_AMSW-7

### PR DESCRIPTION
**Pull request by anotheredward**
add local storage to avoid initial loading issues, also means we now have a baseline of IE8

### CODE REVIEW

**Comment by matt-in-a-hat** [comment]
This doesn't seem like that much of a useful step by itself. I thought adding local storage was so that you can save many rows back and produce a better trend?

**Comment by matt-in-a-hat** [comment]
you already had the baseline IE9 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

**Comment by anotheredward** [comment]
Good to know :)

**Comment by anotheredward** [comment]
We're currently waiting to hear back from the client on what they want in terms of trends.
It's very useful to get rid of the loading screen that they see every minute or so when the page is reloaded :).

**Pull request merged**
